name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore SpaceInvaders.sln

      - name: Build
        run: dotnet build SpaceInvaders.sln --configuration Release --no-restore

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS deps
        run: npm ci

      - name: Run JS unit tests (Vitest)
        run: npm test --silent

      - name: Publish SpaceInvaders.Web
        run: dotnet publish SpaceInvaders.Web/SpaceInvaders.Web.csproj -c Release -o out/SpaceInvaders.Web

      - name: Publish Asteroids.Web
        run: dotnet publish Asteroids.Web/Asteroids.Web.csproj -c Release -o out/Asteroids.Web
